export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'

export const PURCHASE_BUGGER_SUCCESS = 'PURCHASE_BUGGER_SUCCESS'
export const PURCHASE_BUGGER_FAIL = 'PURCHASE_BUGGER_FAIL'
export const PURCHASE_BUGGER_START = 'PURCHASE_BUGGER_START'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'
